import { T as attr, S as pop, Q as push } from "../../../chunks/index.js";
const Gokul = "/_app/immutable/assets/gokul-croped-256.Dk2_6RoB.png";
function About($$payload) {
  $$payload.out += `<section class="flex gap-5 mb-16 items-center"><img class="rounded-3xl hidden lg:block svelte-1v4a30t"${attr("src", Gokul)} alt="Gokul's Image Generated by AI"> <div><h1 class="mb-4 text-4xl font-bold">👋 Hey, I'm Gokul Venkatraman</h1> <div class="flex gap-2 *:text-gray-400 flex-wrap whitespace-nowrap max-w-[400px] md:w-full overflow-auto *:bg-neutral-700 *:rounded-md *:px-4 *:py-1 my-4 *:text-xs *:sm:text-sm font-medium"><p>Founding Engineer</p> <p>Frontend Engineer</p> <p>FullStack Engineer</p> <p>AI Engineer</p></div> <p class="max-w-xl text-lg text-gray-300">Founder-minded engineer building fast, AI-powered, and scalable apps. From startup backends to
      slick mobile UIs — I ship at speed.</p> <div class="mt-6 space-x-4"><a href="/Gokul_Full_Stack_Dev.pdf" class="rounded-xl bg-white/75 px-4 py-2 font-semibold text-black">📄 Resume</a> <a href="mailto:gokul@example.com" class="rounded-xl border border-white px-4 py-2">📬 Contact</a></div></div> <p class="text-[100px] leading-none text-white sm:block hidden"> /></p></section>`;
}
function _layout($$payload, $$props) {
  push();
  let { children } = $$props;
  $$payload.out += `<div class="bg-gray-950 max-w-6xl mx-auto px-4 py-10 text-white sm:px-10">`;
  About($$payload);
  $$payload.out += `<!----> `;
  children($$payload);
  $$payload.out += `<!----></div>`;
  pop();
}
export {
  _layout as default
};
