<script>
  import GokulImg from '$lib/assets/gokul-croped-256.png'


  const onProfileImgClicked = () => {
    // @ts-ignore
    gtag("event", "custom_button_click", {
      button_name: "ProfileImgButton",
      page_location: window.location.href,
    });
  }


</script>

<section class="flex gap-5 mb-16 items-center">

  <button onclick={onProfileImgClicked}>
    <img class="rounded-3xl hidden lg:block" src={GokulImg} alt="Profile-img Generated by AI" />
  </button>

  <div>
    <h1 class="mb-4 text-4xl font-bold">👋 Hey, I'm Gokul Venkatraman</h1>

    <div class="flex gap-2 *:text-gray-400 flex-wrap whitespace-nowrap  max-w-[400px] md:w-full overflow-auto  *:bg-neutral-700 *:rounded-md *:px-4 *:py-1 my-4 *:text-xs *:sm:text-sm font-medium">
      <p>Founding Engineer</p>
      <p>Frontend Engineer</p>
      <p>FullStack Engineer</p>
      <p>AI Engineer</p>
    </div>

    <p class="max-w-xl text-lg text-gray-300">
      Founder-minded engineer building fast, AI-powered, and scalable apps. From startup backends to
      slick mobile UIs — I ship at speed.
    </p>

    <div class="mt-6 space-x-4">
      <a href="/Gokul_Full_Stack_Dev.pdf" class="rounded-xl bg-white/75 px-4 py-2 font-semibold text-black">
        📄 Resume
      </a>
      <a href="mailto:gokul@example.com" class="rounded-xl border border-white px-4 py-2">
        📬 Contact
      </a>
    </div>
  </div>

  <p class="text-[100px] leading-none text-white sm:block hidden">&nbsp;/&gt;</p>
</section>

<style>
  img{
    height: auto;
  }
</style>